language: python

python:
  - "2.7"

before_install:
  - git submodule update --init
  - pip install mysql-python
  - pip install pep8

script: 
  - test/test_exe.sh
  - find src/ -name "*.py" | xargs pep8
