---
- hosts: kfcserver
  sudo: yes
  remote_user: root
  tasks:
    - name: update all packages
      yum: name=* state=latest

    - name: be sure httpd is installed
      yum: name=httpd state=installed

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes

    - name: install git
      yum: name=git state=installed
      
    - name: install vim
      yum: name=vim state=installed

    - name: iptables
      lineinfile: dest=/etc/sysconfig/iptables line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT" insertafter="^:OUTPUT " 

    - name: restart iptables
      service: name=iptables state=restarted
