---
- hosts: all
  sudo: yes
  remote_user: root
  tasks:
    - name: update all packages
      apt: update_cache=yes

    - name: install vim
      apt: name=vim state=present

- hosts: web
  sudo: yes
  remote_user: root
  tasks:
    - name: be sure httpd is installed
      apt: pkg=apache2 state=installed

    - name: be sure httpd is running and enabled
      service: name=apache2 state=running enabled=yes

    - name: install git
      apt: pkg=git state=installed
      
    - name: install ufw
      apt: pkg=ufw state=installed
      tags: ufw

    - name: set ufw deny from access
      ufw: policy=deny direction=incoming
      tags: ufw

    - name: allow from http request
      ufw: policy=allow port=80
      tags: ufw

    - name: install pip
      apt: pkg=python-pip state=installed
