---
- hosts: all
  sudo: yes
  remote_user: root
  tasks:
    - name: update all packages
      apt: update_cache=yes

    - name: install vim
      apt: name=vim state=present

- hosts: web
  sudo: yes
  remote_user: root
  tasks:
    - name: be sure httpd is installed
      apt: pkg=apache2 state=installed

    - name: be sure httpd is running and enabled
      service: name=apache2 state=running enabled=yes

    - name: install git
      apt: pkg=git state=installed
      
    - name: install ufw
      apt: pkg=ufw state=installed
      tags: ufw

    - name: enable ufw
      ufw: state=reset

    - name: set ufw deny from access
      ufw: policy=deny direction=incoming
      tags: ufw

    - name: allow from ssh
      ufw: policy=allow port=22
      tags: ufw

    - name: allow from http request
      ufw: policy=allow port=80
      tags: ufw

    - name: enable ufw
      ufw: state=enabled

    - name: install pip
      apt: pkg=python-pip state=installed

    - name: Install mod_wsgi
      apt: pkg=libapache2-mod-wsgi state=installed

    - name: Set mod_wsgi
      shell: >-
          touch /etc/apache2/mods-available/mod_wsgi.load &&
          echo 'LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so'> /etc/apache2/mods-available/mod_wsgi.load

    - name: be sure httpd is running and enabled
      service: name=apache2 state=restarted

    - name: Change Documet Root
      replace:
        dest='/etc/apache2/sites-enabled/000-default.conf'
        regexp='/var/www/html'
        replace='/var/www/web'

    - name: Set figure judging connector
      lineinfile:
        state: present
        dest: /etc/apache2/sites-enabled/000-default.conf
        line: '        WSGIScriptAlias / /var/www/web/wsgi/base.py\n</VirtualHost>'
        insertbefore: '</VirtualHost>'
        regexp: '^</VirtualHost>'

    - name: make web directory
      command: mkdir -p /var/www/web

    - name: be sure httpd is running and enabled
      service: name=apache2 state=restarted

    - name: install mysql 
      apt: name=mysql-server state=installed

    - name: install libmysqlclient-dev
      apt: name=libmysqlclient-dev state=installed

    - name: install python-dev
      apt: name=python-dev state=installed

    - name: install MySQL-python
      pip: name=MySQL-python

    - name: install bottle
      pip: name=bottle

- hosts: mysql 
  sudo: yes
  remote_user: root
  tasks:
    - name: Install MySQL 
      apt: name=mysql-server state=installed

    - name: start mysql
      service: name=mysql state=started

    - name: install ufw
      apt: pkg=ufw state=installed
      tags: ufw

    - name: enable ufw
      ufw: state=reset

    - name: set ufw deny from access
      ufw: policy=deny direction=incoming
      tags: ufw

    - name: allow from ssh
      ufw: policy=allow port=22
      tags: ufw

    - name: allow from http request
      ufw: policy=allow port=3306
      tags: ufw

    - name: enable ufw
      ufw: state=enabled

    - name: install libmysqlclient-dev
      apt: name=libmysqlclient-dev state=installed

    - name: install python-dev
      apt: name=python-dev state=installed

    - name: install pip
      apt: pkg=python-pip state=installed

    - name: install MySQL-python
      pip: name=MySQL-python

    - name: mysql root setting
      mysql_user: name=developer password=developer host="%" priv=*.*:ALL,GRANT state=present

    - name: Set to recive all ip address
      replace:
        dest: /etc/mysql/my.cnf
        regexp: '^bind-address'
        replace: '#bind-address'
        backup: yes

    - name: start mysql
      service: name=mysql state=restarted
